name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.22' # O la versión que necesites

    - name: Build
      run: cmake --build . --config Release

    - name: Package
      run: |
        mkdir artifacts
        cp path/to/compiled/linux/executable artifacts/

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-app
        path: artifacts/

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.22' # O la versión que necesites

    - name: Build
      run: cmake --build . --config Release

    - name: Package
      run: |
        mkdir artifacts
        cp path/to/compiled/windows/executable artifacts/

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-app
        path: artifacts/
